config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :foundations do
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'add_favorite'
      delete 'remove_favorite'
    end

    collection do
      get 'analytics'
      get 'recommendations'
      get 'my_favorites'
    end
  end

  root 'foundations#index'
end

app/models/foundation.rb
# == Schema Information
#
# Table name: foundations
#
#  id          :integer          not null, primary key
#  address     :string
#  category    :string
#  city        :string
#  description :text
#  latitude    :float
#  longitude   :float
#  name        :string
#  state       :string
#  zipcode     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# app/models/foundation.rb
class Foundation < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_many :events, dependent: :destroy
  has_many :impacts, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_description, against: :description

  enum category: {
    arts: 0,
    education: 1,
    health: 2,
    environment: 3,
    human_services: 4,
    humanitarian: 5,
    animal_welfare: 6,
    artificial_intelligence: 7,
    human_rights: 8,
    conservation: 9,
    food_security: 10,
    youth_development: 11,
    housing: 12,
    children: 13,
    disaster_relief: 14,
    homelessness: 15,
    arts_and_culture: 16,
    social_justice: 17,
    advocacy: 18
  }

  before_save :assign_category

  STATES = [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
    'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
    'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
    'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
    'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
    'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
  ].freeze

  CATEGORY_MAPPING = {
    'Arts Foundation' => :arts,
    'Education Foundation' => :education,
    'Health Foundation' => :health,
    'Environment Foundation' => :environment,
    'Human Services Foundation' => :human_services,
    'Humanitarian Foundation' => :humanitarian,
    'Animal Welfare Foundation' => :animal_welfare,
    'Artificial Intelligence Foundation' => :artificial_intelligence,
    'Human Rights Foundation' => :human_rights,
    'Conservation Foundation' => :conservation,
    'Food Security Foundation' => :food_security,
    'Youth Development Foundation' => :youth_development,
    'Housing Foundation' => :housing,
    'Children Foundation' => :children,
    'Disaster Relief Foundation' => :disaster_relief,
    'Homelessness Foundation' => :homelessness,
    'Arts and Culture Foundation' => :arts_and_culture,
    'Social Justice Foundation' => :social_justice,
    'Advocacy Foundation' => :advocacy
  }.freeze

  def assign_category
    self.category = CATEGORY_MAPPING[name] || :unknown
  end

  def humanized_category
    category.to_s.humanize
  end
end

app/controllers/foundations_controller.rb
class FoundationsController < ApplicationController
  before_action :set_foundation, only: [:show, :edit, :update, :destroy, :add_favorite, :remove_favorite]
  before_action :set_foundations, only: [:index]
  
  def index
    filter_foundations
    apply_sorting

    respond_to do |format|
      format.html
      format.json { render json: @foundations }
    end
  end

  def show
    @latitude = @foundation.latitude
    @longitude = @foundation.longitude
  end

  def new
    @foundation = Foundation.new
  end

  def create
    @foundation = Foundation.new(foundation_params)

    if @foundation.save
      redirect_to @foundation, notice: 'Foundation was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @foundation.update(foundation_params)
      redirect_to @foundation, notice: 'Foundation was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @foundation.destroy
    redirect_to foundations_url, notice: 'Foundation was successfully destroyed.'
  end

  def add_favorite
    current_user.foundations << @foundation
    redirect_to @foundation, notice: 'Foundation was added to your favorites.'
  end

  def analytics
    @foundation_data = Foundation.group(:category).count
  end

  def remove_favorite
    current_user.foundations.delete(@foundation)
    redirect_to @foundation, notice: 'Foundation was removed from your favorites.'
  end

  def recommendations
    if user_signed_in?
      @recommended_foundations = current_user.foundations.flat_map do |foundation|
        Foundation.search_by_description(foundation.description).limit(5)
      end
    else
      redirect_to new_user_session_path, alert: "You need to sign in or sign up to see recommendations."
    end
  end

  def map
    @foundation = Foundation.find(params[:id])
    @latitude = @foundation.latitude
    @longitude = @foundation.longitude
  end

  private

  def set_foundation
    @foundation = Foundation.find(params[:id])
  end

  def set_foundations
    @foundations = Foundation.all
  end

  def filter_foundations
    @foundations = @foundations.where(category: params[:category]) if params[:category].present?
    @foundations = @foundations.where(state: params[:state]) if params[:state].present?
  end

  def apply_sorting
    case params[:sort_by]
    when 'name'
      @foundations = @foundations.order(:name)
    when 'date_added'
      @foundations = @foundations.order(created_at: :desc)
    when 'impact'
      @foundations = @foundations.order(impact_score: :desc)
    end
  end
  
  def foundation_params
    params.require(:foundation).permit(:name, :address, :city, :state, :zipcode, :latitude, :longitude, :description, :category)
  end
end  

app/views/foundations/_form.html.erb
<!-- app/views/foundations/_form.html.erb -->

<%= form_with(model: foundation, local: true) do |form| %>
  <% if foundation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foundation.errors.count, "error") %> prohibited this foundation from being saved:</h2>

      <ul>
        <% foundation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <!-- Add more fields as needed -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foundations/analytics.html.erb
<h1>Foundation Analytics</h1>

<div>
  <h2>Foundations by Category</h2>
  <table>
    <thead>
      <tr>
        <th>Category</th>
        <th>Number of Foundations</th>
      </tr>
    </thead>
    <tbody>
      <% @foundation_data.each do |category, count| %>
        <tr>
          <td><%= Foundation.categories[category] %></td>
          <td><%= count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foundations/anylitics.html.erb
<canvas id="foundation-chart" width="400" height="200"></canvas>

app/views/foundations/index.html.erb
<h1 class="text-center">Foundations</h1>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <h5 class="card-title">Filter by category:</h5>
        <%= select_tag :category, options_for_select(Foundation.categories.keys, params[:category]), include_blank: true, data: { remote: true, url: foundations_path }, class: "form-select custom-select" %>
      </div>

      <div class="col">
        <h5 class="card-title">Filter by state:</h5>
        <%= select_tag :state, options_for_select(Foundation::STATES, params[:state]), include_blank: true, data: { remote: true, url: foundations_path }, class: "form-select custom-select" %>
      </div>

      <div class="col">
        <h5 class="card-title">Sort by:</h5>
        <%= select_tag :sort_by, options_for_select([['Name', 'name'], ['Date added', 'date_added'], ['Impact', 'impact']], params[:sort_by]), include_blank: true, data: { remote: true, url: foundations_path }, class: "form-select custom-select" %>
      </div>
    </div>
  </div>
</div>

<div class="card-body">
  <div class="row">
    <% @foundations.each do |foundation| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title"><%= link_to foundation.name, foundation, class: "card-link" %></h5>
            <p class="card-text"><strong>Address:</strong> <%= foundation.address %></p>
            <p class="card-text"><strong>City:</strong> <%= foundation.city %></p>
            <p class="card-text"><strong>State:</strong> <%= foundation.state %></p>
            <p class="card-text"><strong>Zipcode:</strong> <%= foundation.zipcode %></p>
            <p class="card-text"><strong>Category:</strong> <%= foundation.humanized_category %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/foundations/my_favorites.html.erb
<h1>My Favorite Foundations</h1>

<% if current_user.foundations.any? %>
  <ul>
    <% current_user.foundations.each do |foundation| %>
      <li>
        <%= link_to foundation.name, foundation %>
        <%= foundation.category %>
        <%= foundation.state %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>You have not added any foundations to your favorites yet.</p>
<% end %>

app/views/foundations/new.html.erb
<h1>New Foundation</h1>

<%= render 'form', foundation: @foundation %>

<%= link_to 'Back', foundations_path %>

app/views/foundations/recommendations.html.erb
<h1>Recommended Foundations</h1>

<ul>
  <% @recommended_foundations.each do |foundation| %>
    <li><%= link_to foundation.name, foundation_path(foundation) %></li>
  <% end %>
</ul>

app/views/foundations/show.html.erb
<h1><%= @foundation.name %></h1>

<div class="card">
  <div class="card-body">
    <p class="card-text"><strong>Address:</strong> <%= @foundation.address %>, <%= @foundation.city %>, <%= @foundation.state %> <%= @foundation.zipcode %></p>
    <p class="card-text"><strong>Latitude:</strong> <%= @foundation.latitude %></p>
    <p class="card-text"><strong>Longitude:</strong> <%= @foundation.longitude %></p>
    <p class="card-text"><strong>Description:</strong> <%= @foundation.description %></p>
    <p class="card-text"><strong>Category:</strong> <%= @foundation.category %></p>
  </div>
</div>

<div id="map" class="mt-4" style="height: 400px;"></div>

<script>
  function initMap() {
    var latitude = <%= @foundation.latitude %>;
    var longitude = <%= @foundation.longitude %>;

    var map = new google.maps.Map(document.getElementById('map'), {
      center: { lat: latitude, lng: longitude },
      zoom: 12
    });

    var marker = new google.maps.Marker({
      position: { lat: latitude, lng: longitude },
      map: map,
      title: 'Foundation Location'
    });
  }
</script>

<!-- Include the Google Maps API -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap" async defer></script>