config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :foundations do
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'add_favorite'
      delete 'remove_favorite'
    end

    collection do
      get 'analytics'
      get 'recommendations'
      get 'my_favorites'
    end
  end

  root 'foundations#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foundations</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Add Bootstrap stylesheet -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Add jQuery and Popper.js (required by Bootstrap JavaScript) -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

  <!-- Add Bootstrap JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIeXaLp78fTLjt7BhLkFoWrK8jRyJsZZK+8E6hLJo7oN" crossorigin="anonymous"></script>

  <style>
    /* Custom CSS Styles */
    body {
      background-color: #f8f9fa;
    }

    h1 {
      color: #343a40;
      text-align: center;
      margin-top: 30px;
    }

    .navbar {
      background-color: #007bff; /* Blue */
    }

    .nav-item {
      margin-right: 10px;
    }

    .nav-link {
      color: #ffffff; /* White */
    }

    .card {
      border: none;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }

    .card-title {
      color: #007bff; /* Blue */
      font-size: 18px;
      margin-bottom: 10px;
    }

    .form-select {
      color: #495057;
      background-color: #ffffff;
      border: 1px solid #ced4da;
      border-radius: 0.25rem;
    }

    .notice {
      color: #155724;
      background-color: #d4edda;
      border-color: #c3e6cb;
      padding: 10px;
      margin-bottom: 15px;
    }

    .alert {
      color: #721c24;
      background-color: #f8d7da;
      border-color: #f5c6cb;
      padding: 10px;
      margin-bottom: 15px;
    }
  </style>
</head>

<body>
 <header>
   
<nav class="navbar navbar-expand-lg navbar-light bg-success"> <!-- Use the "bg-success" class for the navbar background color -->
  <%= link_to 'Foundations', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Foundation', new_foundation_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Analytics', analytics_foundations_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'My Favorites', my_favorites_foundations_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Recommendations', recommendations_foundations_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Profile', edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
  </header>

  <main>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>
  </main>
</body>
</html>